import type { EmojiEntry } from "~/composables/useEmojiPickerData";

function entry(input: EmojiEntry): EmojiEntry {
  return input;
}

/** Discord/Slack-style shortcodes beyond the base picker set. */
export const extendedEmojiCatalog: EmojiEntry[] = [
  entry({
    emoji: "🙈",
    name: "see no evil",
    shortcodes: ["see_no_evil"],
    keywords: ["monkey", "hide"],
    category: "smileys",
  }),
  entry({
    emoji: "🙉",
    name: "hear no evil",
    shortcodes: ["hear_no_evil"],
    keywords: ["monkey"],
    category: "smileys",
  }),
  entry({
    emoji: "🙊",
    name: "speak no evil",
    shortcodes: ["speak_no_evil"],
    keywords: ["monkey"],
    category: "smileys",
  }),
  entry({
    emoji: "🙂",
    name: "slight smile",
    shortcodes: ["slight_smile", "slightly_smiling_face"],
    keywords: ["smile"],
    category: "smileys",
  }),
  entry({
    emoji: "😆",
    name: "laughing",
    shortcodes: ["laughing", "laughing_squinting_face"],
    keywords: ["lol"],
    category: "smileys",
  }),
  entry({
    emoji: "😛",
    name: "tongue",
    shortcodes: ["stuck_out_tongue"],
    keywords: ["playful"],
    category: "smileys",
  }),
  entry({
    emoji: "😜",
    name: "wink tongue",
    shortcodes: ["stuck_out_tongue_winking_eye"],
    keywords: ["playful"],
    category: "smileys",
  }),
  entry({
    emoji: "😝",
    name: "squint tongue",
    shortcodes: ["stuck_out_tongue_closed_eyes"],
    keywords: ["playful"],
    category: "smileys",
  }),
  entry({
    emoji: "😐",
    name: "neutral",
    shortcodes: ["neutral_face"],
    keywords: ["meh"],
    category: "smileys",
  }),
  entry({
    emoji: "😑",
    name: "expressionless",
    shortcodes: ["expressionless"],
    keywords: ["blank"],
    category: "smileys",
  }),
  entry({
    emoji: "🙄",
    name: "rolling eyes",
    shortcodes: ["rolling_eyes"],
    keywords: ["sarcasm"],
    category: "smileys",
  }),
  entry({
    emoji: "🤐",
    name: "zipper mouth",
    shortcodes: ["zipper_mouth_face"],
    keywords: ["secret"],
    category: "smileys",
  }),
  entry({
    emoji: "🥴",
    name: "woozy",
    shortcodes: ["woozy_face"],
    keywords: ["drunk"],
    category: "smileys",
  }),
  entry({
    emoji: "😵",
    name: "dizzy",
    shortcodes: ["dizzy_face"],
    keywords: ["shock"],
    category: "smileys",
  }),
  entry({
    emoji: "🤢",
    name: "nauseated",
    shortcodes: ["nauseated_face"],
    keywords: ["sick"],
    category: "smileys",
  }),
  entry({
    emoji: "🤮",
    name: "vomiting",
    shortcodes: ["face_vomiting"],
    keywords: ["sick"],
    category: "smileys",
  }),
  entry({
    emoji: "🥵",
    name: "hot face",
    shortcodes: ["hot_face"],
    keywords: ["heat"],
    category: "smileys",
  }),
  entry({
    emoji: "🥶",
    name: "cold face",
    shortcodes: ["cold_face"],
    keywords: ["freeze"],
    category: "smileys",
  }),
  entry({
    emoji: "🫠",
    name: "melting face",
    shortcodes: ["melting_face"],
    keywords: ["hot"],
    category: "smileys",
  }),
  entry({
    emoji: "😇",
    name: "innocent",
    shortcodes: ["innocent"],
    keywords: ["angel"],
    category: "smileys",
  }),
  entry({
    emoji: "🤡",
    name: "clown",
    shortcodes: ["clown_face"],
    keywords: ["funny"],
    category: "smileys",
  }),
  entry({
    emoji: "💩",
    name: "poop",
    shortcodes: ["poop", "hankey", "shit"],
    keywords: ["funny"],
    category: "smileys",
  }),
  entry({
    emoji: "💀",
    name: "skull",
    shortcodes: ["skull"],
    keywords: ["dead"],
    category: "smileys",
  }),
  entry({
    emoji: "☠️",
    name: "skull crossbones",
    shortcodes: ["skull_and_crossbones"],
    keywords: ["danger"],
    category: "smileys",
  }),
  entry({
    emoji: "👻",
    name: "ghost",
    shortcodes: ["ghost"],
    keywords: ["halloween"],
    category: "smileys",
  }),
  entry({
    emoji: "👽",
    name: "alien",
    shortcodes: ["alien"],
    keywords: ["ufo"],
    category: "smileys",
  }),
  entry({
    emoji: "🤖",
    name: "robot",
    shortcodes: ["robot"],
    keywords: ["bot"],
    category: "smileys",
  }),
  entry({
    emoji: "🧡",
    name: "orange heart",
    shortcodes: ["orange_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💛",
    name: "yellow heart",
    shortcodes: ["yellow_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💚",
    name: "green heart",
    shortcodes: ["green_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💙",
    name: "blue heart",
    shortcodes: ["blue_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💜",
    name: "purple heart",
    shortcodes: ["purple_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "🖤",
    name: "black heart",
    shortcodes: ["black_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "🤍",
    name: "white heart",
    shortcodes: ["white_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💕",
    name: "two hearts",
    shortcodes: ["two_hearts"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💞",
    name: "revolving hearts",
    shortcodes: ["revolving_hearts"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💓",
    name: "beating heart",
    shortcodes: ["heartbeat"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💗",
    name: "growing heart",
    shortcodes: ["heartpulse"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "💖",
    name: "sparkling heart",
    shortcodes: ["sparkling_heart"],
    keywords: ["love"],
    category: "symbols",
  }),
  entry({
    emoji: "👌",
    name: "ok hand",
    shortcodes: ["ok_hand"],
    keywords: ["ok"],
    category: "smileys",
  }),
  entry({
    emoji: "✌️",
    name: "victory",
    shortcodes: ["v", "victory_hand"],
    keywords: ["peace"],
    category: "smileys",
  }),
  entry({
    emoji: "🤞",
    name: "crossed fingers",
    shortcodes: ["crossed_fingers"],
    keywords: ["luck"],
    category: "smileys",
  }),
  entry({
    emoji: "🤟",
    name: "love you gesture",
    shortcodes: ["love_you_gesture"],
    keywords: ["ily"],
    category: "smileys",
  }),
  entry({
    emoji: "🤘",
    name: "horns",
    shortcodes: ["metal", "sign_of_the_horns"],
    keywords: ["rock"],
    category: "smileys",
  }),
  entry({
    emoji: "👊",
    name: "fist",
    shortcodes: ["fist", "facepunch", "punch"],
    keywords: ["bump"],
    category: "smileys",
  }),
  entry({
    emoji: "✊",
    name: "raised fist",
    shortcodes: ["raised_fist"],
    keywords: ["power"],
    category: "smileys",
  }),
  entry({
    emoji: "👆",
    name: "point up",
    shortcodes: ["point_up", "point_up_2"],
    keywords: ["finger"],
    category: "smileys",
  }),
  entry({
    emoji: "👇",
    name: "point down",
    shortcodes: ["point_down"],
    keywords: ["finger"],
    category: "smileys",
  }),
  entry({
    emoji: "👈",
    name: "point left",
    shortcodes: ["point_left"],
    keywords: ["finger"],
    category: "smileys",
  }),
  entry({
    emoji: "👉",
    name: "point right",
    shortcodes: ["point_right"],
    keywords: ["finger"],
    category: "smileys",
  }),
  entry({
    emoji: "🙌",
    name: "raised hands",
    shortcodes: ["raised_hands"],
    keywords: ["celebrate"],
    category: "smileys",
  }),
  entry({
    emoji: "💪",
    name: "muscle",
    shortcodes: ["muscle"],
    keywords: ["strong"],
    category: "smileys",
  }),
  entry({
    emoji: "🦾",
    name: "mechanical arm",
    shortcodes: ["mechanical_arm"],
    keywords: ["prosthetic"],
    category: "smileys",
  }),
  entry({
    emoji: "🐔",
    name: "chicken",
    shortcodes: ["chicken"],
    keywords: ["bird"],
    category: "animals",
  }),
  entry({
    emoji: "🐧",
    name: "penguin",
    shortcodes: ["penguin"],
    keywords: ["bird"],
    category: "animals",
  }),
  entry({
    emoji: "🐝",
    name: "bee",
    shortcodes: ["bee", "honeybee"],
    keywords: ["insect"],
    category: "animals",
  }),
  entry({
    emoji: "🦋",
    name: "butterfly",
    shortcodes: ["butterfly"],
    keywords: ["insect"],
    category: "animals",
  }),
  entry({
    emoji: "🐢",
    name: "turtle",
    shortcodes: ["turtle"],
    keywords: ["slow"],
    category: "animals",
  }),
  entry({
    emoji: "🐍",
    name: "snake",
    shortcodes: ["snake"],
    keywords: ["reptile"],
    category: "animals",
  }),
  entry({
    emoji: "🍉",
    name: "watermelon",
    shortcodes: ["watermelon"],
    keywords: ["fruit"],
    category: "food",
  }),
  entry({
    emoji: "🍩",
    name: "doughnut",
    shortcodes: ["doughnut", "donut"],
    keywords: ["dessert"],
    category: "food",
  }),
  entry({
    emoji: "🍫",
    name: "chocolate",
    shortcodes: ["chocolate_bar"],
    keywords: ["dessert"],
    category: "food",
  }),
  entry({
    emoji: "🍷",
    name: "wine",
    shortcodes: ["wine_glass"],
    keywords: ["drink"],
    category: "food",
  }),
  entry({
    emoji: "🥂",
    name: "champagne",
    shortcodes: ["champagne", "clinking_glasses"],
    keywords: ["celebrate"],
    category: "food",
  }),
  entry({
    emoji: "🎯",
    name: "dart",
    shortcodes: ["dart", "direct_hit"],
    keywords: ["target"],
    category: "activities",
  }),
  entry({
    emoji: "🎲",
    name: "dice",
    shortcodes: ["game_die"],
    keywords: ["game"],
    category: "activities",
  }),
  entry({
    emoji: "🎤",
    name: "microphone",
    shortcodes: ["microphone"],
    keywords: ["sing"],
    category: "activities",
  }),
  entry({
    emoji: "🎧",
    name: "headphones",
    shortcodes: ["headphones"],
    keywords: ["music"],
    category: "activities",
  }),
  entry({
    emoji: "📷",
    name: "camera",
    shortcodes: ["camera"],
    keywords: ["photo"],
    category: "objects",
  }),
  entry({
    emoji: "🎁",
    name: "gift",
    shortcodes: ["gift"],
    keywords: ["present"],
    category: "objects",
  }),
  entry({
    emoji: "📦",
    name: "package",
    shortcodes: ["package"],
    keywords: ["box"],
    category: "objects",
  }),
  entry({
    emoji: "✏️",
    name: "pencil",
    shortcodes: ["pencil"],
    keywords: ["write"],
    category: "objects",
  }),
  entry({
    emoji: "📝",
    name: "memo",
    shortcodes: ["memo", "pencil2"],
    keywords: ["note"],
    category: "objects",
  }),
  entry({
    emoji: "📅",
    name: "calendar",
    shortcodes: ["date", "calendar"],
    keywords: ["schedule"],
    category: "objects",
  }),
  entry({
    emoji: "⏰",
    name: "alarm",
    shortcodes: ["alarm_clock"],
    keywords: ["time"],
    category: "objects",
  }),
  entry({
    emoji: "💤",
    name: "zzz",
    shortcodes: ["zzz"],
    keywords: ["sleep"],
    category: "symbols",
  }),
  entry({
    emoji: "💬",
    name: "speech balloon",
    shortcodes: ["speech_balloon"],
    keywords: ["chat"],
    category: "symbols",
  }),
  entry({
    emoji: "👁️‍🗨️",
    name: "eye speech",
    shortcodes: ["eye_in_speech_bubble"],
    keywords: ["witness"],
    category: "symbols",
  }),
  entry({
    emoji: "♾️",
    name: "infinity",
    shortcodes: ["infinity"],
    keywords: ["forever"],
    category: "symbols",
  }),
  entry({
    emoji: "™️",
    name: "trademark",
    shortcodes: ["tm"],
    keywords: ["legal"],
    category: "symbols",
  }),
  entry({
    emoji: "©️",
    name: "copyright",
    shortcodes: ["copyright"],
    keywords: ["legal"],
    category: "symbols",
  }),
  entry({
    emoji: "®️",
    name: "registered",
    shortcodes: ["registered"],
    keywords: ["legal"],
    category: "symbols",
  }),
  entry({
    emoji: "🇨🇭",
    name: "switzerland",
    shortcodes: ["flag_ch"],
    keywords: ["flag"],
    category: "flags",
  }),
  entry({
    emoji: "🇦🇹",
    name: "austria",
    shortcodes: ["flag_at"],
    keywords: ["flag"],
    category: "flags",
  }),
  entry({
    emoji: "🇳🇱",
    name: "netherlands",
    shortcodes: ["flag_nl"],
    keywords: ["flag"],
    category: "flags",
  }),
  entry({
    emoji: "🇵🇱",
    name: "poland",
    shortcodes: ["flag_pl"],
    keywords: ["flag"],
    category: "flags",
  }),
];
